name: Nowledgeable in github actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
    
    steps:
      - name: Checkout
      uses: actions/checkout@v2
      - run: echo "folder=$(echo $PATH | cut -d ':' -f2)" >> $GITHUB_ENV
      - run: sudo wget https://nowledgeable.com/client/linux -O $folder/nowledgeable && sudo chmod +x $folder/nowledgeable
      - run: nowledgeable run-checks
    