name: Nowledgeable in github actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo $PATH
      - run: echo "folder=$(echo $PATH | cut -d ':' -f2)" >> $GITHUB_ENV
      - run: echo $folder
      - run: ls -la $folder
      - run: sudo wget https://nowledgeable.com/client/linux -O "/home/runner/.local/bin/nowledgeable"
      - run: ls -la $folder
      - run: nowledgeable run-checks
    