name: Nowledgeable in github actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "url=https://nowledgeable.com/client/linux" >> $GITHUB_ENV
      - run: echo "folder=$(echo $PATH | cut -d ':' -f1) >> $GITHUB_ENV"
      - run: echo $folder
      - run: wget $url -O $folder/nowledgeable
      - run: nowledgeable run-checks
    